CREATE TABLE IF NOT EXISTS payment_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id VARCHAR(255),
    external_id VARCHAR(255),
    debtor_iban VARCHAR(255),
    creditor_iban VARCHAR(255),
    amount DOUBLE PRECISION,
    currency VARCHAR(3),
    remittance_info VARCHAR(255),
    requested_execution_date TIMESTAMP,
    status VARCHAR(50),
    creation_date_time TIMESTAMP,
    last_update TIMESTAMP
);
